### ISSUE TITLE
无法导出和保存。

### ISSUE THREAD

**Issue by allenwong** [jaywcjlove/create-custom-symbols#6]
<img width="372" alt="截屏2024-08-28 14 20 24" src="https://github.com/user-attachments/assets/55673dc0-1f41-484f-9d22-fad3b6e6cbee">
这个无法 save 的提示，原因是什么？

**Comment by jaywcjlove** [comment]
@allenwong 什么版本，界面没有保存这个按钮诶，是到处不能到处吗？

**Comment by jaywcjlove** [comment]
@allenwong 我重现了错误，如果文件夹中有个命名相同的 svg 文件，我是先删除再导出，没有权限删除导致的错误，我看一下怎么处理这个错误

**Comment by Cliff-F** [comment]
i just purchased and the same thing happens to me. Unable to export.

**Comment by jaywcjlove** [comment]
@Cliff-F  The file lacks the necessary permissions to be overwritten, which caused the symbol icon export to fail. This issue has been fixed in version 2.4 and is currently awaiting review.

**Comment by jaywcjlove** [comment]
@Cliff-F @allenwong Just released `v2.4`, upgrading to version `v2.4` solves this issue

**Comment by Cliff-F** [comment]
Fixed! Thanks.
